type Query {
    getPosts: [Post]
}

type User {
    _id: ID
    username: String!
    email: String! 
    password: String!
    avatar: String
    joinDate: String
    favorites: [Post]
}

type Post {
    _id: ID
    title: String!
    imageUrl: String!
    categories: [String]!
    excerpt: String!
    textBlock: [TextBlock]!
    createdDate: String
    likes: Int
    createdBy: User!
    messages: [Message]
}

type Message {
    _id: ID
    messageBody: String!
    messageDate: String
    messageUser: User!
}

type TextBlock {
    headline: String
    content: String!
    imageUrl: String
}

type Mutation {
    addPost(title: String!, imageUrl: String!, categories: [String]!, excerpt: String!, creatorId: ID!): Post!
    signupUser(username: String!, email: String!, password: String!): User!
}